export const UserActionTypes = {
  SET_USER_AUTH: "SET_USER_AUTH",
  SET_CURRENT_USER: "SET_CURRENT_USER",
  SET_FRIENDSLIST: "SET_FRIENDSLIST",
  SET_NOTIFICATION: "SET_NOTIFICATION",
  SET_SOCKET: "SET_SOCKET",

  UPDATE_CURRENT_USER: "UPDATE_CURRENT_USER",
  UPDATE_FRIENDSLIST: "UPDATE_FRIENDSLIST",
  UPDATE_NOTIFICATION: "UPDATE_NOTIFICATION"
};
