export const UserActionTypes = {
  SET_USER_AUTH: "SET_USER_AUTH",
  SET_CURRENT_USER: "SET_CURRENT_USER",
  SET_SOCKET: "SET_SOCKET",
  UPDATE_CURRENT_USER: "UPDATE_CURRENT_USER",
  UPDATE_USER_PROPS: "UPDATE_USER_PROPS"
};
